Book store pag sort swag impl
waspp01/online-book-store-app pull request #4
Opened 2023-09-13 16:45 UTC by waspp01

2023-09-13 17:23 UTC, aaananas approved these changes

2023-09-26 16:24 UTC, Rommelua requested changes
Better create a new separate branch for each task.

2023-09-26 16:24 UTC, Rommelua commented on src/main/java/com/example/onlinebookstore/dto/user/UserRegistrationRequestDto.java
> +    @ValidEmail
you can use jakarta.validation.constraints.Email;

2023-09-26 16:24 UTC, Rommelua commented on src/main/java/com/example/onlinebookstore/pom.xml
What is it? Delete this file

2023-09-26 17:03 UTC, closed without merging