8th commit:
waspp01/online-book-store-app pull request #7
Opened 2023-10-19 14:47 UTC by waspp01

- Added ShoppingCart Entity, Service, Repository, DTOs , Controller, Mapper
- Added CartItem entity, DTOs, Service, Repository, Mapper
- Added ShoppingCart creation to UserServiceImpl
- Added required liquibase changes

2023-10-20 10:40 UTC, kerrrusha requested changes
consider to improve your commit naming in future

2023-10-20 10:40 UTC, kerrrusha commented on src/main/java/com/example/onlinebookstore/controller/ShoppingCartController.java
> +@RequestMapping(value = "/cart")
```suggestion
@RequestMapping("/cart")
```

2023-10-20 10:40 UTC, kerrrusha commented on src/main/java/com/example/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +        List<CartItem> cartItems = shoppingCart.getCartItems();
consider extracting this check to the separate method

2023-10-20 13:50 UTC, waspp01 commented
> consider to improve your commit naming in future

What do you mean? Should I add some info about implemented things instead of just number of commit?

2023-10-20 13:50 UTC, waspp01 commented
> consider to improve your commit naming in future

What do you mean? Should I add some info about implemented things instead of just number of commit?

2023-10-29 11:31 UTC, kerrrusha commented
> > consider to improve your commit naming in future
> 
> What do you mean? Should I add some info about implemented things instead of just number of commit?

yeah :)

2023-10-29 11:32 UTC, kerrrusha approved these changes

2023-11-06 19:22 UTC, merged